### PR TITLE
Optional bytes

### LINKED ISSUE #4: Required/optional default value differences.
I noticed that `Encode()` assumes that all `[]byte` are required fields by default but assumes that pointers are optional by default. Is this difference intentional? Is so, we should probably make this fact clearer in the examples as it (for me at least) was unexpected.

### PR DESCRIPTION
**Pull request by aounleonardo**
[]byte was considered a special case in `value()`. I removed the case to allow byte slices to go through the `slice()` method like any other slice. This allows a nil []byte to be considered an empty slice as it used to happen with []int or other slices.

Closes #4

### CODE REVIEW

File: encode.go [hunk 1]
```diff
@@ -228,6 +216,7 @@ func (en *encoder) value(key uint64, val reflect.Value, prefix TagPrefix) {
 
 	// Length-delimited slices  or byte-vectors.
 	case reflect.Slice, reflect.Array:
+
```
Comment (ineiti) [inline encode.go]: remove empty line after `case` - also for `default:` and other cases.

**Comment by ineiti** [comment]
It looks like this has the changes of #43 in it, too. Please make each PR only having the changes necessary.

**Comment by aounleonardo** [comment]
Ok changes done, sorry about the similarity with #43, I might have started solving both on the same branch. Will keep that in mind for next time.
